
name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
      options: --user root

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fix permissions
      run: |
        chown -R root:root .

    - name: Build with Buildozer
      run: |
        buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
